Feature/user model
2023-AlphaProject/iBelieveSurvey_backend pull request #13
Opened 2023-03-22 15:24 UTC by Eun-sun-Lee

## 개요
- user model 생성

## 작업사항
- user model field 작성 
- survey model에서 user PK foreign key로 연결
- user model 폴더 구조 변경

## 변경로직
- 내용을 적어주세요.

2023-03-23 02:07 UTC, koomchang commented on webapp/survey/models/survey.py
> +from user.models.user import User
models 폴더 안에 __init__.py 설정을 해줘서 import 할때
`from user.models import User`
로도 import 가 가능할거에요! 한번 해보고 되면 수정 부탁드려요!

2023-03-23 02:09 UTC, koomchang commented on webapp/user/migrations/__init__.py
migrations 폴더를 직접 만든건가요? 이건 docker build 하면 자동으로 생기니깐 build해서 만들어 주시면 좋을 것 같아요!

build 해서 오류 안 나는지 확인도 필요하니까 migration은 그렇게 처리해주시면 될 것 같아요

2023-03-23 02:25 UTC, koomchang commented on webapp/user/models/user.py
> +    )
p3 : kakao_id를 pk로 지정하지 말고 unique=True 만 지정해주는건 어떨가요? 저희가 사용하다보면 나중에 user_id를 이용해야 하는 일이 생길 수도 있을 것 같아서 제안해봅니다!

2023-03-23 02:27 UTC, koomchang requested changes
리뷰 확인 부탁드려요 !

2023-03-23 02:35 UTC, KimChanJin97 commented on webapp/user/models/user.py
> +        verbose_name="생년월일",
p3: 카카오로그인에서 가져오는 필드가 **년도** 뿐만이 아니라 **월, 일**까지 가져오기 때문에 변수명을 birth_year에서 birth로 고치는게 좋다고 생각해요

2023-03-23 09:02 UTC, Eun-sun-Lee commented on webapp/user/models/user.py
> +        verbose_name="생년월일",
DB field에 birth_year로 돼있길래 그대로 했는데, DB field명도 birth로 바꾸도록 하겠습니다 !

2023-03-23 09:14 UTC, Eun-sun-Lee commented on webapp/user/models/user.py
> +    )
카카오 로그인에서 우리 서비스에 이미 가입한 회원인 경우와 처음 가입한 경우에 따라 redirect를 다르게 해주어야 하는데, user_id(1,2,3,...)로 pk값을 설정 시 이 값을 이용하여 위의 두가지 경우를 구분하지 못하게 됩니다. 그렇기 때문에 카카오톡에서 회원별로 고유하게 부여하는 kakao_id(ex) 20442922)를 PK로 설정하는게 낫지 않을까요 ?

2023-03-23 09:34 UTC, Eun-sun-Lee commented on webapp/user/migrations/__init__.py
app 생성하니까 migrations 폴더 자동으로 생성됐던거 같은데, 그러면 저 migrations 폴더는 그냥 삭제해주면 될까요?

2023-03-24 01:26 UTC, koomchang commented on webapp/user/models/user.py
> +    )
아아 그렇군요! 알겠습니다!

2023-03-24 01:27 UTC, koomchang commented on webapp/user/migrations/__init__.py
build 해면 migration 파일이 자동으로 생성될겁니다! 빌드도 해서 파일도 같이 올리시면 될 것 같아요! build를 해야 오류가 있는지 없는지 확인이 되니까요!

2023-03-24 01:29 UTC, koomchang approved these changes
build하는 것만 체크 한번 하고 merge 하면 될 것 같아요!

2023-03-24 03:12 UTC, Eun-sun-Lee commented on webapp/user/migrations/__init__.py
빌드하고 다시 커밋한건데, 기존 user model 안에 migration 폴더가 있어서인진 모르겠지만 뭐가 달라진지 모르겠더라구요 ,, 일단 merge하면 될까요 ?

2023-03-24 03:14 UTC, koomchang commented on webapp/user/migrations/__init__.py
빌드했을때 문제 없었으면 merge 해주세요!

2023-03-24 06:08 UTC, merged