Feat/user chanjin
2023-AlphaProject/iBelieveSurvey_backend pull request #22
Opened 2023-03-26 14:29 UTC by KimChanJin97

## 개요
1. user model gender choice man은 1로, woman은 2로 수정
2. user admin 등록안해놓아서 기본 유저모델로 적용되어 있었음. admin에 은선이가 만든 user 모델 등록

## 작업사항
- 위와 동일

## 변경로직
- 위와 동일

2023-03-26 14:35 UTC, koomchang commented on webapp/gifticon/models/gifticon.py
> +    )
p2: 전송 여부는 sent, not sent, booleanfield로 하는게 맞지 않을가요? 굳이 integerfield 로 하신 이유가 있으신가요?

2023-03-26 14:35 UTC, koomchang commented on webapp/gifticon/models/gifticon.py
> +    if_sent = models.BigIntegerField(
p2: is_sent의 변수명이 더 적당해 보입니다

2023-03-26 14:36 UTC, koomchang commented on webapp/gifticon/models/gifticon.py
> +    )
p2: user foreignkey 말고 charfield로 하는 이유가 있나요?

2023-03-26 14:38 UTC, koomchang commented on webapp/user/models/user.py
>      )
p3: 이건 은선님 pr에 리뷰했어야 했는데 남녀도 boolean field가 낫지 않을가요?

2023-03-26 14:38 UTC, koomchang commented on webapp/user/models/user.py
> +    birth = models.DateTimeField(
p1: datetimefield 대신 datefield가 더 적당해 보입니다.

2023-03-26 14:39 UTC, koomchang requested changes
고생하셨습니다. 리뷰 확인 부탁드려요

2023-03-26 14:39 UTC, KimChanJin97 commented on webapp/gifticon/models/gifticon.py
> +    )
수정하겠습니다

2023-03-26 14:39 UTC, KimChanJin97 commented on webapp/gifticon/models/gifticon.py
> +    if_sent = models.BigIntegerField(
수정하겠습니다

2023-03-26 16:18 UTC, KimChanJin97 commented on webapp/gifticon/models/gifticon.py
> +    )
수정할게요 ㅠ

2023-03-27 02:31 UTC, KimChanJin97 commented on webapp/user/models/user.py
> +    birth = models.DateTimeField(
수정했습니다

2023-03-27 02:33 UTC, KimChanJin97 commented on webapp/user/models/user.py
>      )
수정했습니다

2023-03-27 03:00 UTC, koomchang approved these changes
LGTM

2023-03-27 04:46 UTC, merged