chore: cart, order, template 모델 추가 & gifticon 모델 삭제
2023-AlphaProject/iBelieveSurvey_backend pull request #53
Opened 2023-05-15 09:52 UTC by KimChanJin97

## 개요
cart, order, template 모델 추가 & gifticon 모델 삭제

## 작업사항
- gifticon 모델이 template 모델로 대체되었습니다

## 변경로직
- 위와 동일

2023-05-15 12:34 UTC, koomchang commented on webapp/cart/models.py
> +    quantity = models.IntegerField(verbose_name="템플릿 수량", null=False)
템플릿 수량이 아니라 상품 수량이 맞는 것 같습니다

2023-05-15 12:35 UTC, koomchang commented on webapp/order/models.py
> +    template_token = models.CharField(max_length=200, verbose_name="템플릿 토큰", null=False)  # 외부로 노출되지 않도록 주의
template에서 template_token을 불러올 수 있는거 아닌가요?

2023-05-15 12:36 UTC, koomchang requested changes
코멘트 확인 바랍니다~

2023-05-15 12:52 UTC, KimChanJin97 commented on webapp/order/models.py
> +    template_token = models.CharField(max_length=200, verbose_name="템플릿 토큰", null=False)  # 외부로 노출되지 않도록 주의
response에 token을 주지 않더라구요. 고민 좀 해야할 것 같아요.
가장 비효율적인 방법은 template객체 하나하나마다 직접 token필드를 해시화하여 대입하는거에요

2023-05-15 12:53 UTC, KimChanJin97 commented on webapp/cart/models.py
> +    quantity = models.IntegerField(verbose_name="템플릿 수량", null=False)
수정하겠습니다. 이것 이외에도 response으로 넘어오는 JSON이 몇가지 제외해야 할 것이 있어서 이것 또한 수정해서 풀리퀘 올리겠습니다.

2023-05-19 17:45 UTC, koomchang commented on webapp/cart/models.py
> +from template.models.template import Template
`from template.models import Template`
로 바꿔주세요

2023-05-20 12:05 UTC, koomchang approved these changes

2023-05-21 08:04 UTC, merged