feat: swagger 테스트 view, url 수정
2023-AlphaProject/iBelieveSurvey_backend pull request #9
Opened 2023-03-21 07:17 UTC by KimChanJin97

## 개요
- swagger 적용 코드 수정

## 작업사항
- survey.views 에서 TestView 삭제
- webapp.urls 에서 url 수정

## 변경로직
- localhost 에서 SurveyView 만 확인됨
- localhost 에서 바로 swagger 확인할 수 있도록 수정

2023-03-21 07:49 UTC, koomchang requested changes
comment 확인 해주세요!

2023-03-21 07:49 UTC, koomchang commented on webapp/config/urls.py
> +    path('surveys', include(('survey.urls', 'api'))),
surveys -> surveys/ 로 바꿔주세요.

convention 에 맞춰 통일 해두어야 나중에 오류가 안 나요

2023-03-22 02:18 UTC, KimChanJin97 commented on webapp/config/urls.py
> +    path('surveys', include(('survey.urls', 'api'))),
앗 죄송함다! 수정하고 올릴게요!

2023-03-22 02:25 UTC, koomchang approved these changes
LGTM

2023-03-22 02:27 UTC, koomchang approved these changes
LGTM

2023-03-22 02:35 UTC, merged